### ISSUE TITLE
New hetzner robot login page broke script

### ISSUE THREAD

**Issue by mullnerz** [br0ziliy/hetzner-robot-dns#2]
Hetzner changed the login page url (and maybe other things), hence the script is not working anymore.

Really appreciate you work, hope you could make this work again.
Thanks you very much!

**Comment by petzoldf** [comment]
@mullnerz   any luck with the new new login page ??? do you solve the problem?

**Comment by petzoldf** [comment]
https://github.com/petzoldf/hetzner-robot-dns

**Comment by mullnerz** [comment]
Thank you @petzoldf, works like a charm!
Why do you not create a pull request?

**Comment by petzoldf** [comment]
In the meantime i have created an pull-request and my commit was merged in
the original branch.

2017-10-19 9:25 GMT+02:00 Zoltán Müllner <notifications@github.com>:
